on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Hello, World!"
      - name: Insert one-line to readme
        run: |
          echo "Hello, World!" >> README.md
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Add 'Hello, World!' to README"
          git push
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Hello, World!"